spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url:  jdbc:mysql://localhost:3306/LibCreat?createDatabaseIfNotExist=true
    username: root
    password: ifsp

  jpa:
    show-sql: true